swagger: '2.0'
info:
  version: '1.0.0'
  title: POOSD - Group 1
  description: ''
  contact:
    url: https://github.com/UCF-GroupProj/poosd-monorepo
host: api.poosd.zhiyan114.com
basePath: /
schemes:
  - https
  - http
servers:
  - url: http://localhost:8080
  - url: https://api.poosd.zhiyan114.com
paths:
  /login:
    post:
      summary: Log in a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
              password:
                type: string
      responses:
        200:
          description: User logged in successfully
          schema:
            type: object
            properties:
              token:
                type: string
                description: JWT token
        401:
          description: Invalid credentials
        403:
          description: Account Not Enabled
          schema:
            type: string
        500:
          description: Server error
  /register:
    post:
      summary: Register a new user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            required:
              - username
              - email
              - password
            properties:
              username:
                type: string
              email:
                type: string
                format: email
              password:
                type: string
      responses:
        201:
          description: User registered successfully
        400:
          description: Invalid input
        500:
          description: Server error