openapi: 3.1.0
info:
  title: POOSD - Group 1
  contact:
    url: https://github.com/UCF-GroupProj/poosd-monorepo
  version: '1.0.0'
servers:
  - url: http://localhost:8080
  - url: https://api.poosd.zhiyan114.com
paths:
  /login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
        '401':
          description: Invalid credentials
          content:
            text/plain: 
              schema:
                type: string
        '403':
          description: Account Not Enabled
          content:
            text/plain: 
              schema:
                type: string
        '500':
          description: Server error
          content:
            text/plain: 
              schema:
                type: string
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User registered successfully
          content:
            text/plain: 
              schema:
                type: string
        '400':
          description: Malformed Body
          content:
            text/plain: 
              schema:
                type: string
        '409':
          description: Duplicate Records (such as email)
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Server error
          content:
            text/plain: 
              schema:
                type: string